from .DQN_Brain import DQN_Brain
from .DDQN_Brain import DDQN_Brain
from .PDQN_Brain import PDQN_Brain
from .PDDQN_Brain import PDDQN_Brain
from .DQN_PER_Brain import DQN_PER_Brain
from .DDQN_PER_Brain import DDQN_PER_Brain
from .DQN_InAday_Brain import DQN_InAday_Brain
from .DQN_PER_Ipm_Brain import DQN_PER_Ipm_Brain
from .DDQN_PER_Ipm_Brain import DDQN_PER_Ipm_Brain
from .PDQN_RePER_Brain import PDQN_RePER_Brain
